### ISSUE TITLE
Issues caused by unsigned code: MacOS prompts damaged, MacOS may not work after new version updates, Windows prompts trojan, etc.

### ISSUE THREAD

**Issue by ZacharyL2** [ZacharyL2/KeyEcho#18]
As this open-source project currently doesn't provide code signing for all platforms and only uses [GitHub Actions](https://github.com/ZacharyL2/KeyEcho/actions) for simple build releases, you might encounter some of the issues mentioned above. This issue collects related problems and provides temporary solutions.

- macOS warning about being damaged: Currently, it uses `"signingIdentity": "-"` to bypass signing. You need to go to "Security & Privacy" in macOS settings and choose "Open Anyway."

- macOS not working after updates: I suspect this might be due to the inconsistency in code signing with each new build version. You may need to remove and re-add (input monitoring) permissions after each update.
	<img width="487" alt="339296976-4d62d705-4a7a-435b-b834-c8bb17e09b88" src="https://github.com/ZacharyL2/KeyEcho/assets/62339765/494005bf-cc4c-4036-aa80-377f0bd53dab">

- Windows warning about malware: I haven't encountered this issue on Win11 Pro, but some versions of Windows (or certain security software) might show this alert. You can choose to ignore it.

**Comment by TheSethRose** [comment]
These were the exact steps for how I fixed the issue with macOS showing “App is damaged and should be moved to trash” warning on MacOS 15 (Sequoia), as mentioned in the original comment.

> macOS warning about being damaged: Currently, it uses "signingIdentity": "-" to bypass signing. You need to go to "Security & Privacy" in macOS settings and choose "Open Anyway."

1. Open **System Settings** → **Privacy & Security**.
2. Scroll down to **Security** and set **Allow apps downloaded from** to **App Store and identified developers**.
3. Try opening the app again. If you still get the warning:
   - Go back to **System Settings** → **Privacy & Security**.
   - Look for an option that says **Open Anyway** under **Security** (it should appear shortly after attempting to open the app).
   - Click **Open Anyway** to allow the app to run.
   
This should let you bypass the warning and run the app without further issues.

**Comment by fulldecent** [comment]
![Screenshot 2024-11-04 at 15 26 49](https://github.com/user-attachments/assets/13c6ae2c-f3dd-4e18-9d5a-4d40bd502ee8)

still an issue

**Comment by mayurankv** [comment]
You need to unquarantine the app: `sudo xattr -cr /Applications/KeyEcho.app` (obviously do your own research before you decide to do this to ensure you are confident in what you are doing and satisfied the app is safe).

EDIT: This does let you open the app, but now I'm having some weird issue where I can't download any sounds and even manually installing as in the CustomSounds.md file has no effect :((

EDIT 2: I could also open this by repeating the previous step by Cmd-Clicking the application and following the same steps in system preferences as for the dmg. However in all cases, the `soundpack.config.json` file is not generated which means I cannot proceed to test the app.

**Comment by ZacharyL2** [comment]
KeyEcho 1.0 now ships signed and verified installers for Windows and macOS. The Windows installer uses Authenticode. The macOS builds are signed with Developer ID, notarized, stapled, and verified before release. The old instructions for bypassing signature checks no longer apply, so I am going to close this tracking issue. If v1 still shows a security warning, please share the exact filename, SHA-256, OS version, and a screenshot of the warning so I can investigate that build separately.
